name: Trigger CI/CD Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-build-and-push:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/build-and-push.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}  

  trigger-install-and-deploy:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/install-and-deploy.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}  
