name: Trigger CI/CD Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-build-and-push:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/build-and-push.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
      ACR_LOGIN_SERVER: publicacrdmsnortheurope.azurecr.io
    secrets: inherit

  trigger-install-and-deploy:
    runs-on: ubuntu-latest
    needs: trigger-build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Install Docker and Deploy Workflow
        uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/install-and-deploy.yml@main
        with:
          ACR_NAME: publicacrdmsnortheurope
          IMAGE_NAME: gettodo
          ACR_LOGIN_SERVER: publicacrdmsnortheurope.azurecr.io
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
