name: Trigger CI/CD Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Build and Push Workflow
        uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/build-push.yml@main
        with:
          ACR_NAME: publicacrdmsnortheurope
          IMAGE_NAME: gettodo

  trigger-install-and-deploy:
    runs-on: ubuntu-latest
    needs: trigger-build-and-push 

    steps:
      - name: Trigger Install Docker and Deploy Workflow
        uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/install-docker.yml@main
        with:
          ACR_NAME: publicacrdmsnortheurope
          IMAGE_NAME: gettodo
