name: Trigger CI/CD Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-build-and-push:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/build-push.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
    secrets: inherit  # Optionally inherit secrets if needed

  trigger-install-and-deploy:
    needs: trigger-build-and-push 
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/install-docker.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
    secrets: inherit  # Optionally inherit secrets if needed
