name: Trigger CI/CD Workflows

on:
  push:
    branches:
      - main

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  trigger-build-and-push:
    uses: Azure-Landing-Zone-Learn/cicd-workflows/.github/workflows/build-and-push.yml@main
    with:
      ACR_NAME: publicacrdmsnortheurope
      IMAGE_NAME: gettodo
      ACR_LOGIN_SERVER: publicacrdmsnortheurope.azurecr.io
      AZURE_CREDENTIALS: AZURE_CREDENTIALS
